<?php

namespace Database\Factories;

use App\Models\Category;
use App\Models\Product;
use App\Models\Season;
use Illuminate\Database\Eloquent\Factories\Factory;

class ProductFactory extends Factory
{
    protected $model = Product::class;

    public function definition(): array
    {
        return [
            'reference_code' => strtoupper($this->faker->unique()->bothify('REF###')),
            'name'           => $this->faker->unique()->words(3, true),
            // slug is auto-generated by HasSlug trait from 'name'
            'description'    => $this->faker->sentence(),
            'base_price'     => $this->faker->randomFloat(2, 10000, 100000),
            'is_active'      => true,
            'season_id'      => Season::factory(),
            'category_id'    => Category::factory(),
        ];
    }

    public function inactive(): static
    {
        return $this->state(['is_active' => false]);
    }
}
